language: c++
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      compiler:
        - gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - COMPILER_ID="gcc"
        - SET_CMAKE_CXX_FLAGS='-Wall -std=c++1z'
        - DO_DEPLOY="y"
        - CODE_COV="n"
    - os: linux
      compiler:
        - clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-5.0
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - COMPILER_ID="clang"
        - SET_CMAKE_CXX_FLAGS='-Wall -std=c++1z'
        - DO_DEPLOY="y"
        - CODE_COV="n"
    - os: linux
      compiler:
        - gcc
      addons:
        apt:
          packages:
            - libsdl2-dev
            - g++-4.8
      env:
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
        - COMPILER_ID="gcc-4.8"
        - SET_CMAKE_CXX_FLAGS='-Wall -std=c++11'
        - DO_DEPLOY="n"
        - CODE_COV="n"
    - os: linux
      compiler:
        - clang
      addons:
        apt:
          packages:
            - clang-3.5
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CC=clang-3.5 && CXX=clang++-3.5"
        - COMPILER_ID="clang-3.5"
        - SET_CMAKE_CXX_FLAGS='-Wall -std=c++11'
        - DO_DEPLOY="n"
        - CODE_COV="n"
    - os: linux
      compiler:
        - gcc
      addons:
        coverity_scan:
          project:
            name: "icecream95/zxtk"
            description: "Build submitted via Travis CI"
          notification_email: "nosuchaddress@example.com"
          build_command_prepend: "sudo mkdir -p /usr/lib/cmake/SDL2/ && sudo cp sdl2-config.cmake /usr/lib/cmake/SDL2/sdl2-config.cmake && mkdir -p build && cd build && cmake .. -DCMAKE_CXX_FLAGS='-Wall -std=c++1z' && make clean && cov-configure --comptype gcc --compiler gcc-7 --template && cp ../coverity_build.sh ."
          build_command:   "sh -e coverity_build.sh"
          branch_pattern: coverity_scan
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
            - g++-7
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - COMPILER_ID="gcc"
        - SET_CMAKE_CXX_FLAGS='-Wall -std=c++1z -fprofile-arcs -ftest-coverage'
        - DO_DEPLOY="n"
        - CODE_COV="y"
        - COV_DEBUG_COMMAND="cat /home/travis/build/icecream95/zxtk/cov-int/scm_log.txt"
env:
  global:
    - secure: "rtNmICrZHxBIRQhxqJAFAqIhJBDTqoV6lcPannTs8Zzj/bAXKGrSx08pMay4meVfUkv+L8fBcdqDHwHm+JhKiHQsBeuXzfCg+HLX61W9myTijlqWvYJLF5Q1rBd1IB8dfEq9BPaYoHe/jNs7GIRfJAWOJXMdPlY7f9i7Bc4NpPo9YRPwkC/qyNXdL22WnXZr453Z8FeSg6/q/rzuUQcgVCJ0Z4mRPgBVa/cNo24kny1zDAnc883S/Y7xGEt7r55rOo9uqDUktQnXvTb3Tq6IULcKE9YYc9ND9FaDEyjB8gLJSOzlYBSieKVV2Pe2K7NEpvY90+UI1s9JU7zAHBZJ0DQRE/2YvggfMX/Zt0sB4UkPGpU7LpUsz/WnNqPzb5wVupbnvnNTSLI9x9/PvNRuAXGjypWhHa8If/xWx6BW5Rm6D9Z9MT/8BCdPvog4q3zJ4nvSPIchHbOJqGJxIm2Wpcp0MAQ2DCNjnT7mdGL9WrWEFL2nj+MZb4YX3dSup+40fgKUvNSD0X9b+VdxP0DzXAs1aXeAlHm5+d+YgK0CauBxB3UTaknTsz4Ti5MCxRVVjYjC8L0LPKsUuLAM2x2M2dhDeq30AK/nB1QMnXZ1MINbyibrz69JsJ7JhTSxhhLfazkFvSxaW08uxwConl99/Ge3HFfX3NTDdxlRafWD+A4="
before_install:
  - eval $MATRIX_EVAL
  - if [ "${CODE_COV}" == "y" ];then sudo pip install codecov;fi
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
# install:
#  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
script:
  - sudo mkdir -p /usr/lib/cmake/SDL2/
  - sudo cp sdl2-config.cmake /usr/lib/cmake/SDL2/sdl2-config.cmake
  - git submodule init
  - git submodule update
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_CXX_FLAGS="${SET_CMAKE_CXX_FLAGS}" -DCMAKE_INSTALL_PREFIX='../install'
  - make -j8
  - make install
  - cd ..
  - mkdir zxtk
  - cd zxtk
  - tar cjvf zxtk_amd64.tar.gz ../install
  - ../build/tests
  - if [ "${CODE_COV}" == "y" ];then cd .. && sh -e get_code_cov.sh && codecov;fi
after_success:
  # Codecov
  - if [ "${CODE_COV}" == "y" ];then cd ${TRAVIS_BUILD_DIR} && lcov --directory . --capture --output-file coverage.info && lcov --remove coverage.info '/usr/*' --output-file coverage.info && lcov --list coverage.info && bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports";fi
  - ${COV_DEBUG_COMMAND}
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: icecream95/icecream95.github.io
  target_branch: zxtk-linux-amd64-$COMPILER_ID
  on:
    branch: master
    condition: $DO_DEPLOY = "y"
