language: c++
sudo: required
os: linux
dist: trusty
compiler:
 - gcc
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libsdl2-dev
     - g++-7
before_install:
 - eval "CC=gcc-7 && CXX=g++-7"
script:
 - sudo mkdir -p /usr/lib/cmake/SDL2/
 - sudo cp sdl2-config.cmake /usr/lib/cmake/SDL2/sdl2-config.cmake
 - mkdir build
 - cd build
 - cmake .. -DCMAKE_CXX_FLAGS='-Wall' -DSDL_DIR=/usr/
 - make -j8
 - mkdir ../install
 - mkdir ../install/bin
 - cp zxtk ../install/bin
 - mkdir ../install/lib
 - cp libload.a libmemory.a ../install/lib
 - cd ..
 - git clone https://github.com/icecream95/icecream95.github.io.git zxtk
 - cd zxtk
 - tar cjvf zxtk_amd64.tar.gz ../install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: icecream95/icecream95.github.io
  target_branch: master
  on:
    branch: master
