language: c++
sudo: required
os: linux
dist: trusty
compiler:
 - gcc
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libsdl2-dev
     - g++-7
before_install:
 - eval "CC=gcc-7 && CXX=g++-7"
 - sudo add-apt-repository ppa:fcitx-team/toolchain -y
 - sudo apt-get update -q
 - sudo apt-get install -y extra-cmake-modules
script:
 - mkdir build
 - cd build
 - cmake .. -DCMAKE_CXX_FLAGS='-Wall'
 - make -j8
deploy:
  skip_cleanup: true

