language: c++
sudo: required
os: linux
dist: trusty
compiler:
 - gcc
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libsdl2-dev
     - g++-7
before_install:
 - eval "CC=gcc-7 && CXX=g++-7"
script:
 - install sdl2-config.cmake /usr/lib/cmake/SDL2/sdl2-config.cmake
 - mkdir build
 - cd build
 - cmake .. -DCMAKE_CXX_FLAGS='-Wall' -DSDL_DIR=/usr/
 - make -j8
deploy:
  skip_cleanup: true

