version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
before_build:
- cmd: appveyor_before_build.bat
build:
  project: build64/zxtk.sln
  parallel: true
  verbosity: normal
after_build:
- cmd: cd build64 && cmake --build . --target install
clone_folder: c:\projects\zxtk
test_script: c:\projects\zxtk\build64\Release\tests.exe
artifacts:
- path: install
  name: zxtk
